import { Rowdies } from 'next/font/google'
import './globals.css'

const rowdies = Rowdies({ 
  subsets: ['latin'],
  weight: ["300", "400", "700"] })

export const metadata = {
  title: 'Scopes Boxing Club Ottawa',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rowdies.className}>{children}</body>
    </html>
  )
}
